import os

Import('env')
env.SConscript('Geometry/SConscript')
env.SConscript('Physics/SConscript')
env.SConscript('Packing/SConscript')

env.Program('main.exe', ['main.cpp', 'Log.cpp', 'Geometry/Grid.o'], LIBS='tinyxml', LIBPATH='#external/tinyxml')
env.Program('testInit.exe', ['main.cpp', 'Log.cpp', 'Geometry/Grid.o'], LIBS='tinyxml', LIBPATH='#external/tinyxml')