import os

BuildDir('bin', 'src', duplicate=0)

env = Environment(
	platform='win32', 
	ENV = {'PATH' : os.environ['PATH']}, 
	tools=['mingw', 'zip'],
	CPPPATH='#/external')
	
Export('env')

env.SConscript('external/SConscript', 'env')

env.SConscript('bin/SConscript', 'env')
