Import('env')

tiObjs = env.SConscript(dirs='tinyxml', exports='env')

Export('env', 'tiObjs')

env.SConscript(dirs='Simulation', exports=['env', 'tiObjs'])
env.SConscript(dirs='Wrap', exports=['env', 'tiObjs'])
