swig_exe="C:\\_develop\\_local\\swig\\swig.exe" # 1.3.29
python_lib = "C:\\Python\\libs"
python_inc = "C:\\Python\\include"

envWrap = Environment(
    platform='win32',
    tools=['mingw', 'swig'],
    CCFLAGS=['-D_WIN32', '-fpermissive', '-W0', '-I' + '#/src', '-I' + '#/src/Wrap', '-DTIXML_USE_STL'],
    CPPPATH=['#src', '#src/Simulation', '#src/Wrap', python_inc],
    LIBS=['python24'],
    LIBPATH=['.', python_lib],
    SWIG=swig_exe,
    SWIGFLAGS=['-python', '-c++', '-shadow', 
               '-IC:\_develop\WorkspaceB\Veda\src\Simulation',
               '-IC:\_develop\WorkspaceB\Veda\src\Wrap'])
    
Export('env')


objs = []
objs += env.SConscript(dirs='#src/tinyxml', exports='env')
objs += env.SConscript(dirs='#src/Simulation/Packing', exports='env')
objs += env.SConscript(dirs='#src/Simulation/Geometry', exports='env')

env.SharedLibrary('_geometry', ['geometry.i'] + objs)

