Import('env', 'tiObjs')

print "#Simulation SCript"

Export('env')
    
objs = []
objs += tiObjs
objs += env.SConscript(dirs='Packing', exports='env')
    
print "Go build program main.exe"

objs += env.Object('main.cpp')

env.Program('main.exe', objs)